name: Android CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/**'
      - '!.github/workflows/android.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/**'
      - '!.github/workflows/android.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create gradle.properties
        run: |
          echo "storeFile=$GITHUB_WORKSPACE/key.store
          storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}
          keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}
          keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" > $GITHUB_WORKSPACE/signing.properties

      - name: Create gradle.properties
        run: |
          ls signing.properties

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Create gradle.properties
        run: |
          find -type f -name '*.apk'

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Debug
          path: app/build/outputs/apk/debug
          retention-days: 7
